server:
  port: "8080"
mysql:
  host: "127.0.0.1"
  port: 3306
  user: "zhisuo"
  password: "zhisuo123!"
  name: "zhisuo"
  charset: "utf8mb4"
  parse_time: "True"
  loc: "Local"
cache:
  type: "memory"
  ttl: 300
redis:
  host: "127.0.0.1"
  port: 6379
  db: 0
log:
  level: "debug"
  file: "logs/dev.log"
  max_size: 100
  max_age: 30
  max_backups: 7
